# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ruki/Documents/Developer/MachineLearning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ruki/Documents/Developer/MachineLearning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruki/Documents/Developer/MachineLearning/CMakeFiles /Users/ruki/Documents/Developer/MachineLearning/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruki/Documents/Developer/MachineLearning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FMTest

# Build rule for target.
FMTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FMTest
.PHONY : FMTest

# fast build rule for target.
FMTest/fast:
	$(MAKE) -f CMakeFiles/FMTest.dir/build.make CMakeFiles/FMTest.dir/build
.PHONY : FMTest/fast

#=============================================================================
# Target rules for targets named FMTrain

# Build rule for target.
FMTrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FMTrain
.PHONY : FMTrain

# fast build rule for target.
FMTrain/fast:
	$(MAKE) -f CMakeFiles/FMTrain.dir/build.make CMakeFiles/FMTrain.dir/build
.PHONY : FMTrain/fast

FM_test.o: FM_test.cpp.o

.PHONY : FM_test.o

# target to build an object file
FM_test.cpp.o:
	$(MAKE) -f CMakeFiles/FMTest.dir/build.make CMakeFiles/FMTest.dir/FM_test.cpp.o
.PHONY : FM_test.cpp.o

FM_test.i: FM_test.cpp.i

.PHONY : FM_test.i

# target to preprocess a source file
FM_test.cpp.i:
	$(MAKE) -f CMakeFiles/FMTest.dir/build.make CMakeFiles/FMTest.dir/FM_test.cpp.i
.PHONY : FM_test.cpp.i

FM_test.s: FM_test.cpp.s

.PHONY : FM_test.s

# target to generate assembly for a file
FM_test.cpp.s:
	$(MAKE) -f CMakeFiles/FMTest.dir/build.make CMakeFiles/FMTest.dir/FM_test.cpp.s
.PHONY : FM_test.cpp.s

FM_train.o: FM_train.cpp.o

.PHONY : FM_train.o

# target to build an object file
FM_train.cpp.o:
	$(MAKE) -f CMakeFiles/FMTrain.dir/build.make CMakeFiles/FMTrain.dir/FM_train.cpp.o
.PHONY : FM_train.cpp.o

FM_train.i: FM_train.cpp.i

.PHONY : FM_train.i

# target to preprocess a source file
FM_train.cpp.i:
	$(MAKE) -f CMakeFiles/FMTrain.dir/build.make CMakeFiles/FMTrain.dir/FM_train.cpp.i
.PHONY : FM_train.cpp.i

FM_train.s: FM_train.cpp.s

.PHONY : FM_train.s

# target to generate assembly for a file
FM_train.cpp.s:
	$(MAKE) -f CMakeFiles/FMTrain.dir/build.make CMakeFiles/FMTrain.dir/FM_train.cpp.s
.PHONY : FM_train.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FMTest"
	@echo "... FMTrain"
	@echo "... FM_test.o"
	@echo "... FM_test.i"
	@echo "... FM_test.s"
	@echo "... FM_train.o"
	@echo "... FM_train.i"
	@echo "... FM_train.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

